version: '3.8'

services:
  db:
    image: postgres:14
    container_name: event_db
    restart: always
    environment:
      POSTGRES_DB: eventapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: event_backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=eventapp
      - JWT_SECRET=sua_chave_secreta_supersegura
    depends_on:
      - db

volumes:
  pgdata:
